### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by ShimizuKosuke19910320** [ShimizuKosuke19910320/chat-space#10]
# IPアドレス
18.182.222.175

**Comment by mo1015** [comment]
清水さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○Editボタンの見た目が見本と異なる
○contents上部のメンバー名の下に線が入っていない
○サイドバーのグループ名、最新メッセージの表示位置が見本と異なる
○投稿メッセージの表示位置が見本と異なる**
<img width="1440" alt="修正２" src="https://user-images.githubusercontent.com/62644781/80270576-453d2a00-86f4-11ea-9e32-dd93d7c9e362.png">

↓参考仕様書
<img width="735" alt="cs仕様書" src="https://user-images.githubusercontent.com/62644781/80270580-4a01de00-86f4-11ea-899c-b7a0daba48b1.png">

**○画面を縮小すると、投稿フォームの画像アイコンが見切れてしまう**

<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/80270582-50905580-86f4-11ea-8657-dbb9f2b29f3d.png">

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ShimizuKosuke19910320** [comment]
ご指摘ありがとうございます。
修正いたしました。
恐れ入りますが、挙動確認お願いいたします。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
